### PR TITLE
Django 1.10 support

### LINKED ISSUE #7: Django 1.10 dropped optparse support
As a result https://github.com/ojii/django-better-test/blob/master/better_test/management/commands/test.py#L26 must be rewritten for argparse

### PR DESCRIPTION
**Pull request by ojii**
Will eventually fix #7 and #8

### CODE REVIEW

**Comment by yakky** [comment]
@ojii when testing this on Django 1.10 with django CMS i get:

```
Traceback (most recent call last):
File "./manage.py", line 335, in <module>
    **dynamic_configs
File "/srv/dev/virtualenvs/cms-3.4-1.10/local/lib/python2.7/site-packages/app_manage/core.py", line 41, in main
    execute_from_command_line(argv)
File "/srv/dev/virtualenvs/cms-3.4-1.10/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
File "/srv/dev/virtualenvs/cms-3.4-1.10/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
File "/srv/dev/virtualenvs/cms-3.4-1.10/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
File "/srv/dev/virtualenvs/cms-3.4-1.10/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
File "/srv/dev/virtualenvs/cms-3.4-1.10/local/lib/python2.7/site-packages/better_test/management/commands/test.py", line 25, in <module>
    class Command(DjangoTest):
File "/srv/dev/virtualenvs/cms-3.4-1.10/local/lib/python2.7/site-packages/better_test/management/commands/test.py", line 26, in Command
    option_list = DjangoTest.option_list + (
AttributeError: type object 'Command' has no attribute 'option_list'
```

**Comment by ojii** [comment]
Looks like you didn't install this branch or it loads the wrong thing, because line 26 should be https://github.com/ojii/django-better-test/blob/66434d47f2825fd9b3d4417164040f11c577f81b/better_test/management/commands/test.py#L26.

**Comment by yakky** [comment]
@ojii indeed. Sorry, pip fooled me. It's all fine

**Comment by ojii** [comment]
merged. also pushed to pypi this time.

**Pull request merged**
